### ISSUE TITLE
Add link to documentation in list.

### ISSUE THREAD

**Issue by JoeJasinski** [ImaginaryLandscape/django-version-viewer#10]
There might be a way to get a hold of the url defined in setup.py for each project. This could be used to create direct links to each project. 

Recommended by: 
https://www.reddit.com/r/django/comments/6am7fg/django_version_viewer_see_which_python_package/

**Comment by db654** [comment]
Closed with https://github.com/ImaginaryLandscape/django-version-viewer/commit/b9dcd9ffdc2c37c51c8f88eb51c3e4bec8488062
